[package]
name = "ggos"
version = "0.1.0"
authors = ["Gary Gan <garyglgan@gmail.com>"]
edition = "2018"

[dependencies]
bootloader = "0.8.0"
volatile = "0.2.6"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]